## Snakemake - Chromatin Assembly
## NCMI, CSIRO
##
## Caitlin Cherryh, 2025
## Developed using scripts from Erin Hahn and Jiri Stiller

## Caitlin's notes
# Run script from dir that contains chromatin-assembly dir (not from within chromatin-assembly/)

# --- Config file --- #
configfile: "config/chromatin_assembly_config.yml"


# --- Global Variables --- #
REF_SPECIES = config["ref_species"]
OUTDIR      = config["repo_dir"] + "results/" + config["ref_species"] + "/"
SAMPLE      = config["input"]["sample"]

REF_GENOME_ID = config["input"]["reference_genome_id"]

READ_DIR    = config["repo_dir"] + config["merge_reads"]["read_dir"]
READ_SAMPLE = config["merge_reads"]["read_path_pattern"]
READ_LANES  = config["merge_reads"]["read_lanes"]

KALIGN_ID = config["s4_read_alignment"]["kalign_id"]

ADAPTERS    = config["repo_dir"] + config["params"]["adapters"]


# --- Complete pipeline run --- #
# Run all rules
rule run_all:
    input:
        s1_masked  = OUTDIR + config["output_dir"]["step1"] + "/" + REF_GENOME_ID + ".masked",
        s1_index  = OUTDIR + config["output_dir"]["step1"] + "/" + REF_GENOME_ID + ".masked.index",
        s2_r1      = OUTDIR + config["output_dir"]["step2"] + "/" + SAMPLE + "_fastqc_R1.fastq.html",
        s2_r2      = OUTDIR + config["output_dir"]["step2"] + "/" + SAMPLE + "_fastqc_R2.fastq.html",
        s3_r1      = OUTDIR + config["output_dir"]["step3"] + "/" + SAMPLE + "_withUMI_R1.fastq.gz",
        s3_r2      = OUTDIR + config["output_dir"]["step3"] + "/" + SAMPLE + "_withUMI_R2.fastq.gz",
        s4_algnmt  = OUTDIR + config["output_dir"]["step4"] + "/" + SAMPLE + "_kalign_" + KALIGN_ID + "_alignment.sam",
        s5_dedup   = OUTDIR + config["output_dir"]["step5"] + "/" + SAMPLE + "alignment_dedup.bam",
        s6a_2bit   = OUTDIR + config["output_dir"]["step6a"] + "/" + SAMPLE + "_TwoBitGenome.2bit",
        s6b_gSize  = OUTDIR + config["output_dir"]["step6b"] + "/" + SAMPLE + "_effGenSize.txt",
        s6c_GCfreq = OUTDIR + config["output_dir"]["step6c"] + "/" + SAMPLE + "_computeGCbias.txt",
        s6d_GCbias = OUTDIR + config["output_dir"]["step6d"] + "/" + SAMPLE + "_alignment_dedup_gcCorrected.bam",
        s7a_metric = OUTDIR + config["output_dir"]["step7a"] + "/" + REF_SPECIES + "_" + SAMPLE + "_insert_size_metrics.txt",
        s7b_stats  = OUTDIR + config["output_dir"]["step7b"] + "/" + REF_SPECIES + "_" + SAMPLE + "_count.txt",
        s8_danpos  = OUTDIR + config["output_dir"]["step8"] + "/" + REF_SPECIES + "_" + SAMPLE + "_DANPOS.txt"

# --- Pipeline steps --- #
## Step 0: Read collation (SLURM_MergeSamples.sh)
rule s0_merge_samples:
    input:
        r1s = expand("{read_dir}{sample}_L00{lane}_R1.fastq.gz", read_dir = READ_DIR, sample = READ_SAMPLE, lane = READ_LANES),
        r2s = expand("{read_dir}{sample}_L00{lane}_R2.fastq.gz", read_dir = READ_DIR, sample = READ_SAMPLE, lane = READ_LANES)
    output:
        r1_merged = OUTDIR + config["output_dir"]["step0"] + "/" + SAMPLE + "_merged_R1.fastq.gz",
        r2_merged = OUTDIR + config["output_dir"]["step0"] + "/" + SAMPLE + "_merged_R2.fastq.gz"
    params:
        merge_reads = config["merge_reads"]["perform_merge"]
    shell:
        """
        if {params.merge_reads} == TRUE:
            cat {input.r1s} > {output.r1_merged}
            cat {input.r2s} > {output.r2_merged}
        """

## Step 1: Repeat masking with RepeatMasker and suffix array (slurm_waterdragon_RM.sh)
# Original suffix array command:  ngskit4b index -i EWD_hifiasm_HiC.fasta.masked -o EWD_hifiasm_HiC.fasta.masked -r waterdragon
rule s1_mask_repeats:
    input:
        ref_genome = config["input"]["reference_genome_path"]
    output:
        masked = OUTDIR + config["output_dir"]["step1"] + "/" + REF_GENOME_ID + ".masked",
        index  = OUTDIR + config["output_dir"]["step1"] + "/" + REF_GENOME_ID + ".masked.index"
    params:
        outdir              = OUTDIR + config["output_dir"]["step1"] + "/",
        adapter             = ADAPTERS,
        ref_species         = REF_SPECIES, 
        log                 = OUTDIR + config["output_dir"]["step1"] + "/index_logs.log",
        repeatmasker_engine = config["s1_mask_repeats"]["repeatmasker_engine"],
        module_repeatmasker = config["modules"]["repeatmasker"],
        module_kit4b        = config["modules"]["kit4b"]
    shell:
        """
        # touch {output.masked}
        # touch {params.log}
        # touch {output.index}

        module load {params.module_repeatmasker}
        module load {params.module_kit4b}

        mkdir -p {params.outdir}

        RepeatMasker -pa {threads} -qq -dir {params.outdir} -lib {params.adapter} {input.ref_genome} {params.repeatmasker_engine}
        ngskit4b index -i {output.masked} -o {output.index} -r '{params.ref_species}' -T {threads} -F {params.log}
        """

## Step 2: Perform quality control using FastQC (slurm_fastqc.sh)
rule s2_raw_read_QC:
    input:
        r1 = config["input"]["r1"],
        r2 = config["input"]["r2"]
    output:
        r1 = OUTDIR + config["output_dir"]["step2"] + "/" + SAMPLE + "_fastqc_R1.fastq.html",
        r2 = OUTDIR + config["output_dir"]["step2"] + "/" + SAMPLE + "_fastqc_R2.fastq.html"
    params:
        outdir        = OUTDIR + config["output_dir"]["step2"] + "/",
        module_fastqc = config["modules"]["fastqc"]
    shell:
        """
        # touch {output.r1}
        # touch {output.r2}

        module load {params.module_fastqc}

        mkdir -p {params.outdir}

        fastqc -t {threads} {input.r1} {input.r2} -o {params.outdir}
        """

## Step 3: UMI extraction with FGBio and Picard (slurm_extractUMI.sh)
rule s3_extract_UMI:
    input:
        r1 = config["input"]["r1"],
        r2 = config["input"]["r2"]
    output:
        r1 = OUTDIR + config["output_dir"]["step3"] + "/" + SAMPLE + "_withUMI_R1.fastq.gz",
        r2 = OUTDIR + config["output_dir"]["step3"] + "/" + SAMPLE + "_withUMI_R2.fastq.gz"
    params:
        basename             = SAMPLE,
        outdir               = OUTDIR + config["output_dir"]["step3"] + "/",
        unmapped_bam         = OUTDIR + config["output_dir"]["step3"] + "/" + SAMPLE + "_unmapped.bam",
        unmapped_bam_withUMI = OUTDIR + config["output_dir"]["step3"] + "/" + SAMPLE + "_unmapped_withUMI.bam",
        fgbio_params         = config["s3_extract_UMI"]["FGBio_params"],
        module_picard        = config["modules"]["picard"],
        module_fgbio         = config["modules"]["fgbio"]
    shell:
        """
        # touch {output.r1}
        # touch {output.r2}

        module load {params.module_picard}
        module load {params.module_fgbio}

        mkdir -p {params.outdir}
        
        CMD1="java -Xmx4g -jar $PICARD_HOME/picard.jar FastqToSam \
	        F1={input.r1} \
	        F2={input.r2} \
	        O={params.unmapped_bam} \
	        SM={params.basename}"
        eval $CMD1
        
        CMD2="java -Xmx4g -jar $FGBIO_HOME/fgbio-2.0.2.jar ExtractUmisFromBam \
	        -i {params.unmapped_bam} \
	        -o {params.unmapped_bam_withUMI} \
	        {params.fgbio_params}"
        eval $CMD2
        
        CMD3="java -Xmx4g -jar $PICARD_HOME/picard.jar SamToFastq \
	        I={params.unmapped_bam_withUMI} \
	        F={output.r1} \
	        F2={output.r2}" 
        eval $CMD3
        """

## Step 4: Align reads with kalign (slurm_kalign_umi.sh)
rule s4_read_alignment:
    input:
        r1    = rules.s3_extract_UMI.output.r1,
        r2    = rules.s3_extract_UMI.output.r2,
        index = rules.s1_mask_repeats.output.index
    output:
        alignment = OUTDIR + config["output_dir"]["step4"] + "/" + SAMPLE + "_kalign_" + KALIGN_ID + "_alignment.sam"
    params:
        outdir        = OUTDIR + config["output_dir"]["step4"] + "/",
        kalign_params = config["s4_read_alignment"]["kalign_params"],
        log_file      = OUTDIR + config["output_dir"]["step4"] + "/" + SAMPLE + "_kalign_" + KALIGN_ID + ".log",
        module_kit4b  = config["modules"]["kit4b"]
    shell:
        """
        # echo 'Step 4' >> {output.alignment}

        module load {params.module_kit4b}

        mkdir -p {params.outdir}

        ngskit4b kalign \
            {params.kalign_params} \
	        -i {input.r1} \
	        -u {input.r2} \
	        -I {input.index} \
	        -o {output.alignment} \
	        -T {threads} \
	        -F {params.log_file}
        """

## Step 5: Remove PCR and optical duplicates from alignment with Picard (slurm_depup.sh)
rule s5_alignment_deduplication:
    input:
        alignment = rules.s4_read_alignment.output.alignment
    output:
        dedup_alignment = OUTDIR + config["output_dir"]["step5"] + "/" + SAMPLE + "_alignment_dedup.bam"
    params:
        outdir        = OUTDIR + config["output_dir"]["step5"] + "/",
        picard_params = config["s5_alignment_deduplication"]["Picard_params"],
        metrics_file  = OUTDIR + config["output_dir"]["step5"] + "/" + SAMPLE + "_removeduplicates.metrics.txt",
        module_picard = config["modules"]["picard"]
    shell:
        """
        # echo 'Step 5' >> {output.dedup_alignment}

        module load {params.module_picard}

        mkdir -p {params.outdir}

        CMD="java -Xmx4g -jar $PICARD_HOME/picard.jar MarkDuplicates\
            --INPUT {input.alignment} \
            --OUTPUT {output.dedup_alignment} \
            --METRICS_FILE {params.metrics_file} \
            {params.picard_params}"
        eval $CMD
        """

## Step 6a: Generate 2Bit genome with faToTwoBit
rule s6a_two_bit_genome:
    input:
        masked_ref_genome = rules.s1_mask_repeats.output.masked
    output:
        twobit_genome = OUTDIR + config["output_dir"]["step6a"] + "/" + SAMPLE + "_alignment_dedup.2bit"
    params:
        outdir = OUTDIR + config["output_dir"]["step6a"] + "/",
        info   = OUTDIR + config["output_dir"]["step6a"] + "/" + SAMPLE + "_info.tab"
    conda:
        "envs/Step6_utils.yaml"
    shell:
        """
        # echo 'Step 6a' >> {output.twobit_genome}
        
        mkdir -p {params.outdir}

        faToTwoBit {input.masked_ref_genome} {output.twobit_genome}
        twoBitInfo {output.twobit_genome} {params.info}
        """

## Step 6b:  Calculate effective genome size with faCount
rule s6b_effective_genome_size:
    input:
        masked_ref_genome = rules.s1_mask_repeats.output.masked
    output:
        eff_gen_size = OUTDIR + config["output_dir"]["step6b"] + "/" + SAMPLE + "_effGenSize.txt"
    params:
        outdir  = OUTDIR + config["output_dir"]["step6b"] + "/"
    conda:
        "envs/Step6_utils.yaml"
    shell:
        """
        # echo 'Step 6b' >> {output.eff_gen_size}

        mkdir -p {params.outdir}

        faCount {input.masked_ref_genome} > {output.eff_gen_size}
        """

## Step 6c: Compute GC bias with deeptools (slurm_computeGCBias.sh)
rule s6c_compute_GC_bias:
    input:
        dedup_alignment = rules.s5_alignment_deduplication.output.dedup_alignment,
        twobit_genome   = rules.s6a_two_bit_genome.output.twobit_genome,
        eff_gen_size    = rules.s6b_effective_genome_size.output.eff_gen_size
    output:
        freq_file = OUTDIR + config["output_dir"]["step6c"] + "/" + SAMPLE + "_computeGCbias.txt"
    params:
        outdir          = OUTDIR + config["output_dir"]["step6c"] + "/", 
        eff_gen_size    = config["s6b_output"]["effective_genome_size"],
        samtools_index  = OUTDIR + config["output_dir"]["step5"] + "/" + SAMPLE + "_alignment_dedup.bam.bai",
        module_python   = config["modules"]["python"],
        module_samtools = config["modules"]["samtools"]
    shell:
        """
        # echo 'Step 6c' >> {output.freq_file}

        module load {params.module_python}
        module load {params.module_samtools}

        mkdir -p {params.outdir}

        samtools index {input.dedup_alignment}
        
        computeGCBias -b {input.dedup_alignment} --effectiveGenomeSize {params.eff_gen_size} -g {input.twobit_genome} --GCbiasFrequenciesFile {output.freq_file}
        """

## Step 6d: Correct GC bias with deeptools (slurm_correctGCBias.sh)
rule s6d_correct_GC_bias:
    input:
        dedup_alignment = rules.s5_alignment_deduplication.output.dedup_alignment,
        twobit_genome   = rules.s6a_two_bit_genome.output.twobit_genome,
        eff_gen_size    = rules.s6b_effective_genome_size.output.eff_gen_size,
        freq_file       = rules.s6c_compute_GC_bias.output.freq_file
    output:
        gc_corrected = OUTDIR + config["output_dir"]["step6d"] + "/" + SAMPLE + "_alignment_dedup_gcCorrected.bam"
    params:
        outdir          = OUTDIR + config["output_dir"]["step6d"] + "/", 
        eff_gen_size    = config["s6b_output"]["effective_genome_size"],
        module_python   = config["modules"]["python"],
        module_samtools = config["modules"]["samtools"]
    shell:
        """
        # echo 'Step 6d' >> {output.gc_corrected}

        module load {params.module_python}
        module load {params.module_samtools}

        mkdir -p {params.outdir}

        correctGCBias_kalign --bamfile {input.dedup_alignment} --effectiveGenomeSize {params.eff_gen_size} --genome {input.twobit_genome} --GCbiasFrequenciesFile {input.freq_file} -o {output.gc_corrected} -p {threads}
        """

## Step 7a: Calculate alignment statistics with Picard (slurm_sizemetrics.sh)
rule s7a_size_metrics:
    input:
        gc_corrected = rules.s6d_correct_GC_bias.output.gc_corrected
    output:
        size_metrics = OUTDIR + config["output_dir"]["step7a"] + "/" + REF_SPECIES + "_" + SAMPLE + "_insert_size_metrics.txt",
        histogram    = OUTDIR + config["output_dir"]["step7a"] + "/"  + REF_SPECIES + "_" + SAMPLE + "_insert_size_histogram.pdf"
    params:
        outdir        = OUTDIR + config["output_dir"]["step7a"] + "/",
        module_picard = config["modules"]["picard"],
        module_R      = config["modules"]["R"]
    shell:
        """
        # echo 'Step 7a' >> {output.size_metrics}

        module load {params.module_picard}
        module load {params.module_R}

        mkdir -p {params.outdir}

        CMD = "java -Xmx4g -jar $PICARD_HOME/picard.jar CollectInsertSizeMetrics \
          I={input.gc_corrected} \
          O={output.size_metrics} \
          H={output.histogram}"
        eval "$CMD"
        """

## Step 7b: Estimate mean nuclear genome cover with Picard (slurm_read_count_GCcorrect.sh)
rule s7b_read_count:
    input:
        gc_corrected = rules.s6d_correct_GC_bias.output.gc_corrected
    output:
        read_count = OUTDIR + config["output_dir"]["step7b"] + "/" + REF_SPECIES + "_" + SAMPLE + "_count.txt"
    params:
        outdir          = OUTDIR + config["output_dir"]["step7b"] + "/",
        module_samtools = config["modules"]["samtools"]
    shell:
        """
        # echo 'Step 7b' >> {output.read_count}

        module load {params.module_samtools}

        mkdir -p {params.outdir}

        CMD="samtools view -c {input.gc_corrected} -o {output.read_count}"
        eval "$CMD"
        """

## Step 8: Peak analysis using DANPOS3
# Original Slurm script: slurm_dtriple_1_vs_27-29.sh
rule s8_peak_analysis:
    input:
        gc_corrected = rules.s6d_correct_GC_bias.output.gc_corrected
    output:
        danpos_op = OUTDIR + config["output_dir"]["step8"] + "/" + REF_SPECIES + "_" + SAMPLE + "_DANPOS.txt"
    params:
        outdir        = OUTDIR + config["output_dir"]["step8"] + "/",
        module_danpos = config["modules"]["danpos"]
    shell:
        """
        # module load {params.module_danpos}
        #
        # mkdir -p {params.outdir}
        #
        # CMD="python danpos.py dtriple TEST_DIR:INPUT_DIR -o RESULTS_DIR"
        # eval "$CMD"
        echo 'Step 8 rule test' >> {output.danpos_op}
        """


