## Snakemake - Chromatin Assembly
## NCMI, CSIRO
##
## Caitlin Cherryh, 2024
## Developed using scripts from Erin Hahn and Jiri Stiller

## Caitlin's notes
# Run script from dir that contains chromatin-assembly dir (not from within chromatin-assembly/)

## Slurm output file paths
# output file: #SBATCH --error=/log/%x_%A_%a.err 
# error file:  #SBATCH --out=/log/%x_%A_%a.out 

# --- Config file --- #
configfile: "config/chromatin_assembly_config.yml"


# --- Global Variables --- #
REF_SPECIES = config["input"]["ref_species"]
READ_DIR = config["input"]["read_dir"]
SAMPLE = config["input"]["read_path_pattern"]
LANES = config["input"]["read_lanes"]

OUTDIR = "results/" + config["input"]["ref_species"] + "/"
STEP2_NAME = config["output_name"]["step2"]
STEP3_NAME = config["output_name"]["step3"]


# --- Complete pipeline run --- #
# Run all rules
rule run_all:
    input:
        s1_masked  = OUTDIR + config["output_name"]["step1"] + "/" + "masked_ref_genome.fasta",
        s1_index   = OUTDIR + config["output_name"]["step1"] + "/" + "index_masked_ref_genome.fasta",
        s2_r1_zip  = expand("results/{ref_species}/{s2_name}/{sample}{lane}_R1.fastq", ref_species = REF_SPECIES, s2_name = STEP2_NAME, sample = SAMPLE, lane = LANES),
        s2_r2_zip  = expand("results/{ref_species}/{s2_name}/{sample}{lane}_R2.fastq", ref_species = REF_SPECIES, s2_name = STEP2_NAME, sample = SAMPLE, lane = LANES),
        s3_r1_zip  = expand("results/{ref_species}/{s3_name}/{sample}{lane}_R1.fastq", ref_species = REF_SPECIES, s3_name = STEP3_NAME, sample = SAMPLE, lane = LANES),
        s3_r2_zip  = expand("results/{ref_species}/{s3_name}/{sample}{lane}_R2.fastq", ref_species = REF_SPECIES, s3_name = STEP3_NAME, sample = SAMPLE, lane = LANES),
        s4_algnmt  = OUTDIR + config["output_name"]["step4"] + "/alignment.txt",
        s5_dedup   = OUTDIR + config["output_name"]["step5"] + "/alignment_dedup.txt",
        s6a_2bit   = OUTDIR + config["output_name"]["step6a"] + "/TwoBitGenome.txt",
        s6b_gSize  = OUTDIR + config["output_name"]["step6b"] + "/effGenSize.txt",
        s6c_GCfreq = OUTDIR + config["output_name"]["step6c"] + "/computeGCbias.txt",
        s6d_GCbias = OUTDIR + config["output_name"]["step6d"] + "/correctGCbias.txt",
        s7a_metric = OUTDIR + config["output_name"]["step7a"] + "/sizeMetrics.txt",
        s7b_stats  = OUTDIR + config["output_name"]["step7b"] + "/summaryStatistics.txt",
        s8_danpos  = OUTDIR + config["output_name"]["step8"] + "/DANPOS.txt"

# --- Pipeline steps --- #
## Step 1: Repeat masking with RepeatMasker and suffix array (slurm_waterdragon_RM.sh)
# Original suffix array command:  ngskit4b index -i EWD_hifiasm_HiC.fasta.masked -o EWD_hifiasm_HiC.fasta.masked -r waterdragon
rule s1_mask_repeats:
    input:
        ref_genome = config["input"]["reference_genome_filepath"]
    output:
        masked = OUTDIR + config["output_name"]["step1"] + "/masked_ref_genome.fasta",
        index  = OUTDIR + config["output_name"]["step1"] + "/index_masked_ref_genome.fasta"
    params:
        step1_dir   = OUTDIR + config["output_name"]["step1"] + "/",
        adapter     = config["params"]["adapters"],
        ref_species = REF_SPECIES, 
        log   = OUTDIR + config["output_name"]["step1"] + "/index_logs.log"
    shell:
        """
        # module load repeatmasker/4.1.0
        # module load kit4b/200218
        # RepeatMasker -pa {resources.threads} -qq -dir {params.step1_dir} -lib {params.adapter} {input.ref_genome}
        # ngskit4b index -i {output.masked} -o {output.index} -r {params.ref_species} -T {resources.threads} -F {params.log}
        cat {input.ref_genome} > {output.masked}
        cat {input.ref_genome} > {params.log}
        cat {input.ref_genome} > {output.index}
        """

## Step 2: Perform quality control using FastQC (slurm_fastqc.sh)
rule s2_raw_read_QC:
    input:
        r1 = READ_DIR + SAMPLE + "{lane}_R1.fastq",
        r2 = READ_DIR + SAMPLE + "{lane}_R2.fastq"
    output:
        r1_zip = OUTDIR + STEP2_NAME + "/" + SAMPLE + "{lane}_R1.fastq",
        r2_zip = OUTDIR + STEP2_NAME + "/" + SAMPLE + "{lane}_R2.fastq"
    params:
        outdir = OUTDIR + STEP2_NAME + "/"
    shell:
        """
        # module load fastqc/0.11.9 
        # fastqc -t {resources.threads} {input.r1} {input.r2} -o {params.outdir}
        cat {input.r1} > {output.r1_zip}
        cat {input.r2} > {output.r2_zip}
        """

## Step 3: UMI extraction with FGBio and Picard (slurm_extractUMI.sh)
rule s3_extract_UMI:
    input:
        r1_zip = OUTDIR + STEP2_NAME + "/" + SAMPLE + "{lane}_R1.fastq",
        r2_zip = OUTDIR + STEP2_NAME + "/" + SAMPLE + "{lane}_R2.fastq"
    output:
        r1_zip = OUTDIR + STEP3_NAME + "/" + SAMPLE + "{lane}_R1.fastq",
        r2_zip = OUTDIR + STEP3_NAME + "/" + SAMPLE + "{lane}_R2.fastq"
    param:
        basename             = SAMPLE + "{lane}",
        unmapped_bam         = OUTDIR + STEP3_NAME + "/" + SAMPLE + "{lane}_unmapped.bam",
        unmapped_bam_withUMI = OUTDIR + STEP3_NAME + "/" + SAMPLE + "{lane}_unmapped_withUMI.bam",
        fgbio_read_structure = config["s3_extract_UMI"]["FGBio_read_structure"],
        fgbio_mol_index_tags = config["s3_extract_UMI"]["FGBio_molecular_index_tags"],
        fgbio_single_tag     = config["s3_extract_UMI"]["FGBio_single_tag"]
    shell:
        """
        # module load picard
        # module load fgbio
        # 
        # CMD1 = "JAVAOPTS=-Xmx2g java -jar $PICARD_HOME/picard.jar FastqToSam \
	    # 	F1={input.r1_zip} \
	    # 	F2={input.r2_zip} \
	    # 	O={param.unmapped_bam} \
	    # 	SM={param.basename}
        # eval "$CMD1"
        # 
        # CMD2="JAVAOPTS=-Xmx50g java -jar $FGBIO_HOME/fgbio-1.3.0.jar ExtractUmisFromBam \
	    # 	--input={param.unmapped_bam} \
        #   --output={param.unmapped_bam_withUMI} \
	    # 	--read-structure={param.fgbio_read_structure} \
        #   --molecular-index-tags={param.fgbio_mol_index_tags} \
        #   --single-tag={param.fgbio_single_tag}"
        # eval "$CMD2"
        # 
        # CMD3="JAVAOPTS=-Xmx2g java -jar $PICARD_HOME/picard.jar SamToFastq \
	    #   I={param.unmapped_bam_withUMI} \
	    #   F={output.r1_zip} \
	    #   F2={output.r2_zip}" 
        # eval "$CMD3"

        cat {input.r1} > {output.r1_zip}
        cat {input.r2} > {output.r2_zip}
        """

## Step 4: Align reads with kalign (slurm_kalign_umi.sh)
rule s4_read_alignment:
    input:
        r1_zip = OUTDIR + STEP3_NAME + "/" + SAMPLE + "{lane}_R1.fastq",
        r2_zip = OUTDIR + STEP3_NAME + "/" + SAMPLE + "{lane}_R2.fastq",
        index = rules.s1_mask_repeats.output.index
    output:
        alignment = OUTDIR + config["output_name"]["step4"] + "/" + SAMPLE + "_" + config["s4_read_alignment"]["kalign-id"] + "_alignment.sam"
    params:
        kalign-c      = config["s4_read_alignment"]["kalign-c"],
        kalign-l      = config["s4_read_alignment"]["kalign-l"],
        kalign-d      = config["s4_read_alignment"]["kalign-d"],
        kalign-U      = config["s4_read_alignment"]["kalign-U"],
        log_file      = OUTDIR + config["output_name"]["step4"] + "/" + SAMPLE + "_" + config["s4_read_alignment"]["kalign-id"] + ".log"
    shell:
        """
        # module load kit4b/200218
        # CMD="ngskit4b kalign \
        #   --minchimeric={params.kalign-c} \
        #   --minacceptreadlen={params.kalign-l} \
        #   --pairminlen={params.kalign-d} \
        #   --pemode={params.kalign-U} \
	    #   --in={input.r1_zip} \
	    #   --pair={input.r2_zip} \
	    #   --sfx={input.index} \
	    #   --out={output.alignment} \
	    #   --threads={resources.threads} \
	    #   --log={params.log_file}"
        # eval "$CMD"

        echo 'Step 4' >> {output.alignment}
        """

""" 
To input all r1 and all r2 files at once (need to add block comments for SHELL command):
input:
        r1s_zip = expand("results/{ref_species}/{s3_name}/{sample}{lane}_R1.fastq", ref_species = REF_SPECIES, s3_name = STEP3_NAME, sample = SAMPLE, lane = LANES),
        r2s_zip = expand("results/{ref_species}/{s3_name}/{sample}{lane}_R2.fastq", ref_species = REF_SPECIES, s3_name = STEP3_NAME, sample = SAMPLE, lane = LANES),
shell:
        # module load kit4b/200218
        # CMD="ngskit4b kalign \
        #   --minchimeric={params.kalign-c} \
        #   --minacceptreadlen={params.kalign-l} \
        #   --pairminlen={params.kalign-d} \
        #   --pemode={params.kalign-U} \
	    #   --in={input.r1s_zip) \
	    #   --pair={input.r2s_zip} \
	    #   --sfx={input.index} \
	    #   --out={output.alignment} \
	    #   --threads={resources.threads} \
	    #   --log={params.log_file}"
        # eval "$CMD"
"""

## Step 5: Remove PCR and optical duplicates from alignment with Picard (slurm_depup.sh)
rule s5_alignment_deduplication:
    input:
        alignment = rules.s4_read_alignment.output.alignment
    output:
        dedup_alignment = OUTDIR + config["output_name"]["step5"] + "/alignment_dedup.txt"
    params:
        picard_remove_dupes = config["s5_alignment_deduplication"]["Picard_remove_duplicates"],
        picard_barcode_tag = config["s5_alignment_deduplication"]["Picard_barcode_tag"]
    shell:
        """
        # module load picard/2.26.10
        # CMD="JAVAOPTS=-Xmx100g java -jar $PICARD_HOME/picard.jar MarkDuplicates\
        #     I= ${BAM_DIR}/${SLURM_ARRAY_TASK_ID}_*_sorted.bam \
        #     O= ${DEDUP_DIR}/${BASENAME}_dedup.bam \
        #     M= ${LOG_DIR}/${BASENAME}_removeduplicates.metrics.txt \
        #     REMOVE_DUPLICATES={params.picard_remove_dupes} \
        #     BARCODE_TAG={params.picard_barcode_tag}"
        # eval "$CMD"

        echo 'Step 5' >> {output.dedup_alignment}
        """

## Step 6a: Generate 2Bit genome with faToTwoBit
rule s6a_two_bit_genome:
    input:
        masked_ref_genome = rules.s1_mask_repeats.output.masked
    output:
        twobit_genome = OUTDIR + config["output_name"]["step6a"] + "/TwoBitGenome.txt"
    params:
        faToTwoBit = config["params"]["faToTwoBit"]
    shell:
        """
        # {params.faToTwoBit} {input.masked_ref_genome} {output.twobit_genome}
        echo 'Step 6a' >> {output.twobit_genome}
        """

## Step 6b:  Calculate effective genome size with faCount
rule s6b_effective_genome_size:
    input:
        masked_ref_genome = rules.s1_mask_repeats.output.masked
    output:
        eff_gen_size = OUTDIR + config["output_name"]["step6b"] + "/effGenSize.txt"
    params:
        faCount = config["params"]["faCount"]
    shell:
        """
        # {params.faCount} {input.masked_ref_genome} > {output.eff_gen_size}
        echo 'Step 6b' >> {output.eff_gen_size}
        """

## Step 6c: Compute GC bias with deeptools (slurm_computeGCBias.sh)
rule s6c_compute_GC_bias:
    input:
        dedup_alignment = rules.s5_alignment_deduplication.output.dedup_alignment,
        twobit_genome   = rules.s6a_two_bit_genome.output.twobit_genome,
        eff_gen_size    = rules.s6b_effective_genome_size.output.eff_gen_size
    output:
        freq_file = OUTDIR + config["output_name"]["step6c"] + "/computeGCbias.txt"
    shell:
        """
        # module load python/3.9.4
        # module load samtools/1.12
        # CMD="computeGCBias \
        # -b ${BAM_DIR}/${SLURM_ARRAY_TASK_ID}_*_dedup.bam \
        # --effectiveGenomeSize 1716675060 \
        # -g ${BIT_DIR}/GCF_900067755.1_pvi1.1_genomic_RM_nhmm_adapt.2bit \
        # --GCbiasFrequenciesFile ${GC_COMPUTE_DIR}/${BASENAME}.txt"
        # eval "$CMD"

        echo 'Step 6c' >> {output.freq_file}
        """

## Step 6d: Correct GC bias with deeptools (slurm_correctGCBias.sh)
rule s6d_correct_GC_bias:
    input:
        dedup_alignment = rules.s5_alignment_deduplication.output.dedup_alignment,
        twobit_genome   = rules.s6a_two_bit_genome.output.twobit_genome,
        eff_gen_size    = rules.s6b_effective_genome_size.output.eff_gen_size,
        freq_file       = rules.s6c_compute_GC_bias.output.freq_file
    output:
        gc_corrected = OUTDIR + config["output_name"]["step6d"] + "/correctGCbias.txt"
    shell:
        """
        # module load python/3.9.4
        # module load samtools/1.12
        echo 'Step 6d' >> {output.gc_corrected}
        """

## Step 7a: SCalculate alignment statistics with Picard (slurm_sizemetrics.sh)
rule s7a_size_metrics:
    input:
        gc_corrected = rules.s6d_correct_GC_bias.output.gc_corrected
    output:
        size_metrics = OUTDIR + config["output_name"]["step7a"] + "/sizeMetrics.txt"
    shell:
        """
        # module load picard/2.26.10
        # module load R
        echo 'Step 7a' >> {output.size_metrics}
        """

## Step 7b: Estimate mean nuclear genome cover with Picard (slurm_read_count_GCcorrect.sh)
rule s7b_read_count:
    input:
        gc_corrected = rules.s6d_correct_GC_bias.output.gc_corrected
    output:
        summ_stats = OUTDIR + config["output_name"]["step7b"] + "/summaryStatistics.txt"
    shell:
        """
        # module load samtools/1.12
        echo 'Step 7b' >> {output.summ_stats}
        """

## Step 8: Peak analysis using DANPOS3
# Original Slurm script: slurm_dtriple_1_vs_27-29.sh
rule s8_peak_analysis:
    input:
        gc_corrected = rules.s6d_correct_GC_bias.output.gc_corrected
    output:
        danpos_op = OUTDIR + config["output_name"]["step8"] + "/DANPOS.txt"
    shell:
        """
        # module load danpos/3.1.1
        echo 'Step 8' >> {output.danpos_op}
        """
      

