# Chromatin assembly pipeline
# Configuration file

# NOTE: To run pipeline, set working directory to /path/to/chromatin-assembly/ 

# NOTE: pipeline assumptions about read file naming convention
# This pipeline was tested on reads with the structure:
#     {sample_id}_{some_text}_L00{num}_R{1|2}.fastq.gz
# e.g., R114096_22W5TWLT3_TTCTGCGTCG-TTCGTACACC_L001_R1.fastq.gz
# If you have data with a different file name structure, you may have issues running the pipeline.


##### Section 1: Input data and parameters #####
# repo_dir: path to the chromatin-assembly directory (including trailing slash) e.g., /path/to/chromatin-assembly/
#           Remember to include trailing slash!
repo_dir: "/scratch3/che318/chromatin-assembly/"

# ref_species: Species name
ref_species: "mouse"

# binomial_species_name: user-specified species name for use with ngskit index e.g., "Mus musculus"
binomial_species_name: "Mus musculus"

## Effective genome size, extracted from the output of Step 6b
#   The number of non-N bases in the genome i.e., {total len} - {total N}
effective_genome_size: 12003433

## Merging reads ##
## See `README.md` for detailed instructions on merging reads
# read_dir: full path to directory e.g., /full/path/to/chromatin-assembly/data/yeast/reads/ 
# merge_dict: optional filepath specifying lanes to merge and human-readable sample names.
#             see README.md for details
#             To use: specify filepath e.g., "/scratch3/che318/chromatin-assembly/mouse_sample_dict.txt"
#             Otherwise "NA"
# use_merge_dict: "yes" if using merge_dict, otherwise "no"
#             see README.md for details
merge_reads: 
  read_dir: "/scratch3/che318/chromatin-assembly/data/mouse/reads/"
  merge_dict: "/scratch3/che318/chromatin-assembly/mouse_sample_dict.txt"
  use_merge_dict: "no"

## Input data paths and details ##
# reference_genome_id: human-readable identifier for reference genome
# reference_genome_path: full path to reference genome e.g.,  /full/path/to/chromatin-assembly/data/yeast/reference_genome/ref_genome.fsa
# input_samples: The samples to be run through the pipeline e.g., `input_sample_ids: ["id01", "id02", "id03", "id04"]`
#                Each sample ID is a chunk of a filepath. 
#                Important: If you renamed the files using a `merge_dict`, you must specify the sample names here
#                           See README.md for details!
#                Important: the `input_samples` variable should include all samples you wish to use as either 
#                           experimental data or control for Step 8 (Peak analysis with DANPOS)
reference_genome_id: "GRCm38.p6"
reference_genome_path: "/scratch3/che318/chromatin-assembly/data/mouse/reference_genome/GCF_000001635.26_GRCm38.p6_genomic.fna"
input_samples: ["133143", "133133"] 

## Input control for peak analysis with DANPOS (Step 8) ##
# test_name: Descriptive name for test, to be used as name of output directory
# exp_ids: The sample IDs to use as experimental/test data for DANPOS analysis e.g., `exp_ids: ["id01", "id02"]`
#           Should be a subset of `input_samples`
# control_ids: The sample IDs to use as input control for DANPOS analysis e.g., `control_ids: ["id03", "id04"]`
#              Should be a subset of `input_samples`
peak_analysis: 
  test_name: "133143-133133"
  exp_ids: ["133143"] 
  control_ids: ["133133"] 

## Adapters ##
# adapters: file path relative to chromatin-assembly directory i.e., resources/adapters/adap_cont_rna.fa
params:
  adapters: "resources/adapters/adap_cont_rna.fa"


##### Section 2: Output names #####
# Names of the output directory generated for each step
# The relative path to each of these directories is: chromatin-assembly/results/{ref_species}/{stepX}
#     Where:
#         {ref_species} is specified above (Section 1: Input data and parameters)
#         {stepX} is specified below
# For more details, see the section "Running Snakemake pipelines" in the repo `README.md`
output_dir:
  step0: "0_mergedReads"
  step1: "1_repeatmasker"
  step2: "2_fastqc"
  step3: "3_UMIext"
  step4: "4_kalign_UMI"
  step5: "5_dedup"
  step6a: "6a_2BitGenome"
  step6b: "6b_effGenSize"
  step6c: "6c_computeGCbias"
  step6d: "6d_correctGCbias"
  step7a: "7a_alignmentStatistics"
  step7b: "7b_genomeCoverage"
  step8:  "8_dtriple"


##### Section 3: Program parameters #####
# Refer to repo file `doco/05_advanced_use.Rmd` for details on changing program parameters

## Step 0: Merge Reads ##
# short_sample_ID: Defines sample IDs extracted from file paths. Accepted values: "yes" or "no"
#                  If "yes", will define sample ID as anything before first underscore 
#                     (i.e., sample ID is '111' for file 111_22W5TWLT3_TCACACGTGG-TGTATAGGTC_L005_R1.fastq.gz")
#                  If "no", will define sample ID as anything before first underscore 
#                     (i.e., sample ID is '111_22W5TWLT3' for file 111_22W5TWLT3_TCACACGTGG-TGTATAGGTC_L005_R1.fastq.gz")
#                  Recommended: "yes" (especially for merging reads across directories)
s0_merge_repeats:
  short_sample_ID: "true"

## Step 1: RepeatMasker ##
# repeatmasker_engine: user-specified engine for use with RepeatMasker
#                      Recommended: "-engine rmblast"
s1_mask_repeats:
  repeatmasker_engine: "-engine rmblast"

## Program parameters for UMI extraction with FGBio and Picard (Step 3) ##
# FGBio_params: user-specified parameters for FGBio call 
#               Recommended: "-r 8M143T 8M143T -t ZA ZB -s RX"
s3_extract_UMI:
  FGBio_params: "-r 8M143T 8M143T -t ZA ZB -s RX"

## Step 4: kalign parameters ##
# kalign_params: user-specified parameters for kalign call
#                Recommended: `kalign_params: "-c25 -l25 -d50 -U4"`
# kalign_id: user-specified string to be included in output filepath
#            Recommended: "pe_c25_l25_d50_U4"
s4_read_alignment:
  kalign_params: "-c25 -l25 -d50 -U4"
  kalign_id: "pe_c25_l25_d50_U4"

## Step 5: Picard parameters ##
# Picard_params: user-specified parameters for Picard call
#                Recommended: "--REMOVE_DUPLICATES TRUE --BARCODE_TAG RX"
s5_alignment_deduplication:
  Picard_params: "--REMOVE_DUPLICATES TRUE --BARCODE_TAG RX"


##### Section 4: HPC system #####
## Modules - update module versions here if required ##
modules:
  danpos: "danpos/3.1.1"
  fastqc: "fastqc/0.11.9"
  fgbio: "fgbio/2.0.2"
  kit4b: "kit4b/200218"
  picard: "picard/3.0.0"
  python: "python/3.9.4"
  R: "R/4.0.5"
  repeatmasker: "repeatmasker/4.1.2p1"
  samtools: "samtools/1.18.0"

