# Chromatin assembly pipeline
# Configuration file

# Note: Run script from within chromatin-assembly/ dir

input:
  ref_species:                 "central_dragon"
  read_dir:                    "data/reads/"
  read_lanes:                  ["1", "2", "3", "4", "5", "6", "7", "8"]
  read_path_pattern:           "133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L00"
  reference_genome_filepath:   "data/reference_genome/central_dragon_genome.txt"
  input_control_files1:        "data/input_control/Tuna_skink_water_dragon/AGRF_CAGRF220510576_HL7J7DSX3/G-WD-1_HL7J7DSX3_ACTTCTGC-CCGGGACT_L00*"
  input_control_files2:        "data/input_control/Tuna_skink_water_dragon/AGRF_CAGRF220510576_HLT7NDSX3/G-WD-1_HLT7NDSX3_ACTTCTGC-CCGGGACT_L00*" 

params:
  adapters: "resources/adapters/adap_cont_rna.fa"
  faCount:  "resources/faCount" 
  faToTwoBit: "resources/faToTwoBit" 

output_name:
  step1: "1_repeatmasker"
  step2: "2_fastqc"
  step3: "3_UMIext"
  step4: "4_kalign_UMI"
  step5: "5_dedup"
  step6a: "6a_2BitGenome"
  step6b: "6b_effGenSize"
  step6c: "6c_computeGCbias"
  step6d: "6d_correctGCbias"
  step7a: "7a_alignmentStatistics"
  step7b: "7b_genomeCoverage"
  step8:  "8_dtriple"

# Directories and files that may or may not be needed (file paths refer to Petrichor)
potential_input:
  input_dir:            "/scratch3/che318/input/ACC_paper/AGRF_CAGRF22019398_H3NTTDSX3/"
  input_pattern:        "133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L"
  sample_dir:           "/scratch3/che318/input/ACC_paper/AGRF_CAGRF22019398_H3NTTDSX3/"
  output_dir:           "/scratch3/che318/chromatin-assembly/results/"
  reference_genome_dir: "/datasets/work/efsp-faire/work/sti089/genomes/central_dragon/"
  input_control_dir1:   "/datasets/work/efsp-faire/source/Tuna_skink_water_dragon/AGRF_CAGRF220510576_HL7J7DSX3/"
  input_control_dir2:   "/datasets/work/efsp-faire/source/Tuna_skink_water_dragon/AGRF_CAGRF220510576_HLT7NDSX3/" 
  log_dir:              "/scratch3/che318/chromatin-assembly/results/logs/"

