# Chromatin assembly pipeline
# Configuration file

# NOTE: To run pipeline, set working directory to /path/to/chromatin-assembly/ 

# NOTE: pipeline assumptions about read file naming convention
# This pipeline was tested on reads with the structure:
#     {sample_id}_{some_text}_L00{num}_R{1|2}.fastq.gz
# e.g., R114096_22W5TWLT3_TTCTGCGTCG-TTCGTACACC_L001_R1.fastq.gz
# If you have data with a different file name structure, you may have issues running the pipeline.


##### Section 1: Input data and parameters #####
# repo_dir: path to the chromatin-assembly directory (including trailing slash) e.g., /path/to/chromatin-assembly/
#           Remember to include trailing slash!
repo_dir: "/scratch3/che318/chromatin-assembly/"

# ref_species: Species name
ref_species: "gecko"

# Merging reads
# See `README.md` for detailed instructions on merging reads
# Parameters:
# read_dir: full path to directory e.g., /full/path/to/chromatin-assembly/data/yeast/reads/ 
merge_reads: 
  read_dir: "/scratch3/che318/chromatin-assembly/data/gecko/reads/"


# Input data paths and details
# Merged reads will be in directory: /full/path/to/chromatin-assembly/results/{ref_species}/0_mergedReads/
# Parameters:
# reference_genome_id: human-readable identifier for reference genome
# reference_genome_path: full path to reference genome e.g.,  /full/path/to/chromatin-assembly/data/yeast/reference_genome/ref_genome.fsa
# input_sample_ids: The samples to be run through the pipeline. Each sample ID is a chunk of a filepath. 
#             Dictionary of sample IDs i.e., ["sample_1", "sample_2", "sample_3"]
#             Important - keep identation level consistent for all lines in dictionary
#             Note - the `input_sample_ids` should be the sample IDs for the MERGED files
#                   Given the `merge_reads` parameters:
#                          `merge_sample_ids: ["id01", "id02", "id03"]`
#                          `sample_names: ["id01": "name01", "id02": "name02", "id03": "name03"]`
#                   If you used sample IDs when merging reads (`use_names: TRUE`), use the sample IDs here:
#                         `input_sample_ids: ["id01", "id02", "id03"]`
#                   If you used sample names when merging reads (`use_names: TRUE`), use the sample names here:
#                         `input_sample_ids: ["name01", "name02", "name03"]`
#             Note - the input for DANPOS (Step 8) is the output from Step 6 (GC corrected alignment)
#                   so the `input_sample_ids` variable should include all samples you wish to use as either experimental
#                   data OR input control for DANPOS.

# All sample IDs for gecko:
#input_sample_ids: ["R114096", "R122595", "R122596", "R135806", "R135860", "R31499", "R31500",
#                  "R31502", "R54899", "R55025", "R55032", "R55033", "R84119", "R87557", 
#                  "SMZ3538", "SMZ3540", "SMZ3541", "SMZ3557", "SMZ3559", "SMZ3560", "SMZ3561"]

input:
  Reference_genome_id: "gecko_genome"
  reference_genome_path: "/scratch3/che318/chromatin-assembly/data/gecko/reference_genome/gecko_genome.fsa"
  input_sample_ids: ["R55032", "R55025", "SMZ3557", "SMZ3559"] 

# Input control for peak analysis with DANPOS (Step 8)
# Parameters:
# test_name: Descriptive name for test, to be used as name of output directory
# exp_ids: The sample IDs to use as experimental/test data for DANPOS analysis, as a list i.e., e.g., ["id01", "id02", "id03"]
#           Should be a subset of the `input_sample_ids`
# control_ids: The sample IDs to use as input control for DANPOS analysis, as a list i.e., e.g., ["id01", "id02", "id03"]
#              Should be a subset of the `input_sample_ids`
peak_analysis: 
  test_name: "R-S"
  exp_ids: ["R55032", "R55025"] 
  control_ids: ["SMZ3557", "SMZ3559"] 

# Adapters
#   adapters: file path relative to chromatin-assembly directory i.e., resources/adapters/adap_cont_rna.fa
params:
  adapters: "resources/adapters/adap_cont_rna.fa"


##### Section 2: Output names #####
# Names of the output directory generated for each step
# The relative path to each of these directories is: chromatin-assembly/results/{ref_species}/{stepX}
#     Where:
#         {ref_species} is specified above (Section 1: Input data and parameters)
#         {stepX} is specified below
# Changing the output directory here allows you to rerun steps with changed parameters
# Unless you are changing the parameters to rerun a step, you will not need to change these variables
#   Snakemake is smart - it will not overwrite existing files
#   If you want to rerun a step with a different set of input parameters, you can update the output directory
#   for that step here, which will allow you to run that step with the new settings
#   If you want to force Snakemake to rerun a rule, use the flag `-R {rulename}` or `--forcerun {rulename}`
#       e.g., "snakemake -R somerule" will force Snakemake to re-run all jobs of that rule and everything downstream 
output_dir:
  step0: "0_mergedReads"
  step1: "1_repeatmasker"
  step2: "2_fastqc"
  step3: "3_UMIext"
  step4: "4_kalign_UMI"
  step5: "5_dedup"
  step6a: "6a_2BitGenome"
  step6b: "6b_effGenSize"
  step6c: "6c_computeGCbias"
  step6d: "6d_correctGCbias"
  step7a: "7a_alignmentStatistics"
  step7b: "7b_genomeCoverage"
  step8:  "8_dtriple"


##### Section 3: Program parameters #####
# Program parameters for repeat masking with RepeatMasker (Step 1)
#     repeatmasker_engine: user-specified engine for use with RepeatMasker
#     ngskit_index_species_name: user-specified species name for use with ngskit index 
s1_mask_repeats:
  repeatmasker_engine: "-engine rmblast"
  ngskit_index_species_name: "Mus musculus"


# Program parameters for UMI extraction with FGBio and Picard (Step 3)
#   FGBio_params: user-specified parameters for FGBio call (old version: "--read-structure 8M143T 8M143T --molecular-index-tags ZA ZB --single-tag RX")
s3_extract_UMI:
  FGBio_params: "-r 8M143T 8M143T -t ZA ZB -s RX"

# Program parameters for aligning reads with kalign (Step 4)
#   kalign_params: user-specified parameters for kalign call
#       -c, --minchimeric: minimum chimeric length as a percentage of probe length
#                             Default = 0 (to disable), otherwise 15 - 99
#       -l, --minacceptreadlen: after any end trimming only accept read for further processing if read is at least this length (in bp)
#                                   Default = 50, range is 15 - 2000
#       -d, --pairminlen:  accept paired end alignments with observed insert sizes of at least this (in bp)
#                                Default = 100, minimum = 25
#       -U, --pemode: paired end processing mode (default = 0): 
#                         0 - none, 
#                         1 - paired end with recover orphan ends, 
#                         2 - paired end no orphan recovery, 
#                         3 - paired end with recover orphan ends treating orphan ends as SE, 
#                         4 - paired end no orphan recovery treating orphan ends as SE
#   kalign_id: user-specified string to be included in output filepath
s4_read_alignment:
  kalign_params: "-c25 -l25 -d50 -U4"
  kalign_id: "pe_c25_l25_d50_U4"

# Program parameters for removing PCR and optical duplicates from alignment with Picard (Step 5)
#   Picard_params: user-specified parameters for Picard call
s5_alignment_deduplication:
  Picard_params: "--REMOVE_DUPLICATES TRUE --BARCODE_TAG RX"


##### Section 4: Intermediate output #####
# Effective genome size, extracted from the output of Step 6b
#   The number of non-N bases in the genome i.e., {total len} - {total N}
s6b_output:
  effective_genome_size: 12003433


##### Section 5: Modules #####
# For use on the CSIRO HPC system Petrichor
# Update module versions here, as required
modules:
  danpos: "danpos/3.1.1"
  fastqc: "fastqc/0.11.9"
  fgbio: "fgbio/2.0.2"
  kit4b: "kit4b/200218"
  picard: "picard/3.0.0"
  python: "python/3.9.4"
  R: "R/4.0.5"
  repeatmasker: "repeatmasker/4.1.2p1"
  samtools: "samtools/1.18.0"

