---
title: "Troubleshooting"
author: "Caitlin Cherryh"
date: "2025-06-12"
output: html_document
---

## Quick checks:

- What directory are you in? You should be in the directory `chromatin-assembly`.
Check with the command `pwd`:

```
> pwd
/path/to/chromatin-assembly
```

- Try running a dry run with the command `snakemake -n -p -c1` - sometimes you 
might be missing a file or have an incorrect file path

## Potential issues:

- **Snakemake not found?**
  - Check Python module is loaded: `module load python`
  - Check job script includes the line `module load python`
- **Need to specify more threads?**
  - The number of threads for each rule are specified within the Snakefile at 
  `workflow/Snakefile`
  - To update the number of threads, go to the desired rule and change the number
  next to `threads: `
- **Not enough resources supplied in job scripts?**
  - Update resources in SBATCH lines
- **Not enough resources supplied to Snakemake?**
  - Update resources in the `profiles/slurm/config.yaml` file for the problem rule
- **SLURM jobs repeatedly timing out**
  - The default queue on Petrichor has a time limit of 160 hours. You can submit 
  long jobs to the `ext` queue (see 
  [Extended Partitions](https://confluence.csiro.au/pages/viewpage.action?spaceKey=SC&title=Job+queues#Jobqueues-ExtendedPartitions)
  on Confluence), which allows jobs of up to 30 days (`30-00:00:00`)
  - There's two type of jobs that can time out - the main jobscript (which 
  controls Snakemake) and child jobs (submitted by Snakemake to execute pipeline 
  steps). 
  - Fix the main jobscript timing out:
    - Add a line specifying the slurm partition to the top of your script: `#SBATCH --partition=ext`
    - Extend the time for your job e.g., to set a time of 25 days use `#SBATCH --time=25-00:00:00`
  - Fix rules timing out:
    - Open the `profiles/slurm/config.yaml`
    - Go to the section specifying resources for the step that needs more time 
    - Specify the partition to be used: e.g., for Step 4, to use the`ext` partition
    add the line `- s4_read_alignment:slurm_partition=ext`
    - Extend the time for the job e.g., to specify 400 hours for Step 4, edit
    the `s4_read_alignment:runtime` specified to be `- s4_read_alignment:runtime=400h`
    - **Note:** The maximum runtime for a rule will be 720 hours (30 days x 24 hours)
    - Check that the indentation is consistent! Each line specifying rule 
    resources should have the same indentation levels
    - Save the file and try running your jobs
- **Names of read files don't match?**
	- This pipeline was tested on reads with the structure: `{sample_id}_{some_text}_L00{num}_R{1|2}.fastq.gz`
	- For example, `R114096_22W5TWLT3_TTCTGCGTCG-TTCGTACACC_L003_R1.fastq.gz`
	- If you have data with a different file name structure, you may have issues running the pipeline.
	- Potential pitfall: your read filenames have an extra argument after the R1/R2 e.g., `SampleName_S1_L001_R1_001.fastq.gz`
- **Names of merged read files don't match?**
	- This pipeline names merged reads (i.e., the output from Step 0) with the structure: `{sample_id}_merged_R{1|2}.fastq.gz`
	- For example, `R114096_merged_R1.fastq.gz`
	- If you have merged reads with different naming structure, the pipeline will not work
	- Potential pitfall: your merged reads have the file path naming structure: `{sample_id}_R{1|2}_merged.fastq.gz`
- **Added new input files after executing all/part of the pipeline?**
  - Snakemake does not automatically rerun jobs when new input files are added
  - To get a list of the output files that are affected: `snakemake --list-input-changes`
  - To force a rerun of the new input files: `snakemake -n --forcerun $(snakemake --list-input-changes)`
- **Snakemake locked directory and can't run new job?**
  - Try rerunning the Snakemake command with the additional command line. parameter `--unlock`
      - `--unlock` can be used to remove a stale lock, e.g., if the machine powered off or a job was killed while a Snakemake instance was still running
  - Not working? Delete contents of the hidden directory `.snakemake/locks/` and try again
- **Can't generate conda environments?**
  - Try following the instructions from the Confluence [Conda and python in HPC](https://confluence.csiro.au/display/IMT/Conda+and+python+in+HPC)
  page:
    - Load the miniforge module: `module load miniforge3; source /apps/miniforge3/enable_miniforge.sh`
    - Try creating the conda environments again
  - Try creating a test conda environment:
      - **Load miniforge3:** `module load miniforge3; source /apps/miniforge3/enable_miniforge.sh`
      - **Create env:** `conda create --name test_env`
      - If you can't create any conda environments at all, that's an issue for 
      Scientific Computing
- **Issues generating conda environments with Snakemake?**
  - If there's issues because conda environments weren't properly installed,
  delete the contents of the hidden directory `.snakemake/conda/`
  - Then, create conda envs with `snakemake --use-conda --conda-create-envs-only -c1`
- **Step 5 failed with `exit code 1`?**
  - Increase the computational resources provided
  - In the `profiles/slurm/config.yaml` file, go to the following line and increase
  the `mem_mb` provided (default is 50000 mb, try increasing by 5000 mb at a time):
    - `  - s5_alignment_deduplication:mem_mb=50000`
  - In the `config/chromatin-assembly-config.yml` file, go to the following 
  section and increase the memory provided to Java in the `java_mem` var 
  (default is 20GB, try increasing by 5GB at a time):
  ```
  s5_alignment_deduplication:
    Picard_params: "--REMOVE_DUPLICATES TRUE --BARCODE_TAG RX"
    java_mem: "20"
  ```
- **Can't run Step 6a or Step 6b because faCount and faToTwoBit aren't installed?**
  - Check whether the conda environments have been created in the hidden directory `.snakemake/conda/`
  - Try to generate the conda environments using `snakemake --use-conda --conda-create-envs-only -c1` 
  - The conda environment "Step6" is provided at `workflow/envs/Step6.yaml`
  - If this environment isn't working, try creating the environment and manually exporting it:
    - To manually create the environment: `conda env create --name Step6 --file workflow/envs/Step6.yaml`
    - To re-export the environment: `conda activate Step6; conda env export > workflow/envs/Step6.yaml`

