---
title: "Using Snakemake"
author: "Caitlin Cherryh"
date: "2025-05-02"
output: html_document
---

Key points to remember:

- All file paths in this document assume the working directory is the `chromatin-assembly/` folder

-----

## Useful command lines
Load modules needed by Snakemake on Petrichor:
```
module load python
module load graphviz
```

Simplest dry run:
```
snakemake -n -p -c1
```

To merge reads on Petrichor with Slurm:
```
snakemake --slurm --profile profiles/slurm/ --until s0_merge_samples --omit s1_mask_repeats,s2_raw_read_QC,s3_extract_UMI
```

Full run of pipeline on Petrichor with Slurm:
```
snakemake --slurm --profile profiles/slurm/
```

Full run of pipeline on Petrichor with Slurm, skipping read merging:
```
snakemake --slurm --profile profiles/slurm/ --omit s0_merge_samples
```

-----

## Controlling pipeline execution
Instead of running the entire pipeline with 1 core, you can control which
steps are executed and what computational resources are allowed.

To run the entire pipeline with `N` cores: 
```
snakemake -cN
```

To run the pipeline until it reaches a certain rule, use `snakemake --until {target}`
(where `{target}` is the rule name). For example, to execute Steps 1-3:
``` 
snakemake --until s3_extract_UMI  -cN
```

To omit steps from the pipeline (i.e., run the pipeline without executing a
specific rule or any downstream rules) use `snakemake --omit {target}`. 

Any step can be omitted. Execution of the pipeline will stop when downstream rules
become dependent on completion of the target rule.

For example, to omit Step 8 (peak analysis in DANPOS3):
```
snakemake --omit s8_peak_analysis -cN
```

The `--until` and `--omit` flags can be combined.

For example if you want to execute Steps 2-3 (raw read quality control and extract UMIs) 
without executing Step 1 (mask repeats):
```
snakemake --until s3_extract_UMI --omit s1_mark_repeats -cN
```

You can also execute a single rule of the pipeline by using the desired output 
file path with `snakemake -p {output_file_path}`.

-----

## Running the pipeline on a HPC
The current version of Snakemake on Petrichor is v7.24.0.

To get started running the pipeline on Petrichor, see the quick start guide
in `README.md`.

We provide job scripts for your convenience. Each job script performs 1-3 pipeline steps. 
We grouped pipeline steps into job scripts based on the computational resources 
and time required to complete each step.

The following sections of documentation detail how to run Snakemake on a HPC. 
These points have already been incorporated into the included job scripts. Unless 
you are using a different HPC system or running the pipeline in interactive mode
(not using Slurm), you probably will not need the following information.

#### Environment modules
Running Snakemake on Petrichor requires the python module:
```
module load python
```

Outputting graphs (to visualise the pipeline execution) requires the graphviz module:
```
module load graphviz
```
  
#### Running pipeline on the HPC
To run the pipeline on the HPC, you need to include the `--slurm` flag and the 
path to the Slurm profile.

For example:
```
snakemake --slurm --profile profiles/slurm/ 
```

When using a Slurm profile, do not specify the number of cores in the Snakemake 
call. Snakemake determines computational resources for each step from the 
provided profile. 

Additional parameters can be added as described above.

For example, to execute Steps 2-3 without executing Step 1:
```
snakemake --slurm --profile profiles/slurm/ --until s3_extract_UMI --omit s1_mark_repeats
```


#### Specifying resources

To specify account and partition in the command line:
```
snakemake --slurm --default-resources slurm_account=<your SLURM account> slurm_partition=<your SLURM partition>
```

Account and partition details can also be specified using a configuration profile. 
```
snakemake --slurm --profile profiles/slurm/
```

For more details and examples of slurm config profiles, see the [Snakemake-Profiles/slurm](https://github.com/Snakemake-Profiles/slurm) GitHub
repository

Some notes on [Running Snakemake on a cluster](https://docs.s3it.uzh.ch/how-to_articles/how_to_run_snakemake/#resources):

- Resources can be referenced within a rule's `shell` and `run` sections e.g., `{resources.mem_mb}`, `{resources.threads}`
  - This is useful for applications that accept memory or thread parameters in the command line
  - For example, in rule `s2_raw_read_QC`: `fastqc -t {threads} {input.r1} {input.r2} -o {params.outdir}` 
- Snakefiles and configuration profiles can specify both `threads` and `cpus_per_task`
  - `cpus_per_task` is specific to Slurm.
  - `threads` is independent of environment and always available, even when not explicitly set for a rule. 
  - `threads` can be determined based on how well the task can be parallelised
  - Snakemake uses `threads` to determine how many jobs to execute when running a pipeline locally
  
**Note**: Snakemake and Slurm have different names for resources (refer to 
[Advanced Resource Specifications](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#advanced-resource-specifications) )

-----

## Running the pipeline locally

1. Clone the `chromatin-assembly` repository into the location you wish to run 
the pipeline in, then navigate into the `chromatin-assembly` folder. 
2. Copy your input data into the `data/` folder. 
3. Update the file paths and variables within the `config/chromatin-assembly-config.yml`
file.
4. Update the allowed resources for the run in the `profiles/local/config.yaml` 
file. For the local run (which is usually a dry or test run), all rules have 
the same resources.
5. *If using conda environments:* Activate the conda environment: `conda activate snakemake`
6. Perform a dry run with one core (`-c1`): `snakemake -n -p -c1`
7. Run the snakemake pipeline with the local profile:

```
snakemake --profile profiles/local/  
``` 

