---
title: "HPC use for Snakemake Version 8+"
author: "Caitlin Cherryh"
date: "2025-04-15"
output: html_document
---

Key points to remember:

- All file paths in this document assume the working directory is the `chromatin-assembly/` folder

## HPC use for snakemake v8+
The current version of Snakemake on Petrichor is v7.24.0.

From version 8 onwards, the approach for running a Snakemake pipeline on Slurm changes.

This page outlines how to run Snakemake v8+ pipelines on Petrichor.

#### Preparing the conda environment

Snakemake provides a plugin called [snakemake-executor-plugin-slurm](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#snakemake-executor-plugin-slurm) to facilitate Slurm use. 

To create a conda environment for use with Snakemake and Slurm:

- Create new conda environment with the name `slurm_snakemake`
  - `$ conda create -n slurm_snakemake`
- Activate the new environment
  - `$ conda activate slurm_snakemake`
- Configure conda to enable the bioconda channel
  - `$ conda config --add channels bioconda`
  - `$ conda config --add channels conda-forge`
- Load the python module (which contains Snakemake)
  - `$ module load python`
- Load the graphviz module (to allow pipeline visualisation)
  - `$ module load graphviz`
- Install the [snakemake-executor-plugin-slurm](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#snakemake-executor-plugin-slurm) plugin from 
[bioconda](https://anaconda.org/bioconda/snakemake-executor-plugin-slurm) 
  - `$ conda install bioconda::snakemake-executor-plugin-slurm`
- Save a list of the packages in the conda environment as YAML format
  - `$ conda env export -n slurm_snakemake > slurm_snakemake_conda.yaml`
- Save a list of the loaded modules as a text file
  - `$ module list > slurm_snakemake_modules.txt`

#### Specifying resources

To specify account and partition in the command line:
```
snakemake --executor slurm --default-resources slurm_account=<your SLURM account> slurm_partition=<your SLURM partition>
```

Account and partition details can also be specified using a configuration profile. 
```
snakemake --executor slurm --workflow-profile profiles/slurm/config.yaml
```

Some notes on [Running Snakemake on a cluster](https://docs.s3it.uzh.ch/how-to_articles/how_to_run_snakemake/#resources):

- Resources can be referenced within a rule's `shell` and `run` sections e.g., `{resources.mem_mb}`, `{resources.threads}`
  - This is useful for applications that accept memory or thread parameters in the command line
  - For example, in rule `s2_raw_read_QC`: `fastqc -t {resources.threads} {input.r1} {input.r2} -o {params.outdir}` 
- Snakefiles and configuration profiles can specify both `threads` and `cpus_per_task`
  - `cpus_per_task` is specific to Slurm.
  - `threads` is independent of environment and always available, even when not explicitly set for a rule. 
  - `threads` can be determined based on how well the task can be parallelised
  - Snakemake uses `threads` to determine how many jobs to execute when running a pipeline locally
  
**Note**: Snakemake and Slurm have different names for resources (refer to 
[Advanced Resource Specifications](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#advanced-resource-specifications) )


#### Running pipeline on the HPC
1. Clone the `chromatin-assembly` repository into the location you wish to run 
the pipeline in, then navigate into the `chromatin-assembly` folder. 
2. Copy your input data into the `data/` folder. 
3. Update the file paths and variables within the `config/chromatin-assembly-config.yml`
file.
4. Update the Slurm resources in the `profiles/slurm/config.yaml` file
5. Open the conda environment: `conda activate slurm_snakemake`
6. Perform a local dry run to identify any issues:
```
snakemake -n -p -c1
```
7. Execute the desired rules using the `--executor` flag and the slurm workflow profile (and other commands as desired):
```
snakemake --executor slurm --workflow-profile profiles/slurm/ ...
```
If no additional commands are added, Snakemake will execute the entire pipeline.

As when executing locally, pipeline execution can be limited to specific rules
by adding flags to the Snakemake command line call.
For example: 

- Execute read merging (Step 0): `--until s0_merge_samples`
- Execute Steps 1--3: `--until s3_extract_UMI`
- Execute pipeline, omitting Step 8: `--omit s8_peak_analysis`
- Execute Steps 2-3: `--until s3_extract_UMI --omit s1_mark_repeats`

The complete command line to execute Steps 2-3 would be:
```
snakemake --executor slurm --workflow-profile profiles/slurm/ --until s3_extract_UMI --omit s1_mark_repeats
```

## Useful command line options

Some command line options you may find useful.

For further details, see the Snakemake documentation page 
[All command line options](https://snakemake.readthedocs.io/en/stable/executing/cli.html#all-options).

| Command option | Usage example | Explanation |
| --- | --- | --- |
| `--snakefile`, `-s` | `-s {SNAKEFILE}` | Specify the Snakefile. You will not need to specify the Snakefile as input -- by default, Snakemake looks for the snakefile at `Snakefile` and `workflow/Snakefile`. In this repository, the Snakefile is located at `workflow/Snakefile`. Use only if you have a specific snakefile to use in a different location. |
| `--dry-run`, `--dryrun`, `-n` | `-n` | Perform dry run - do not execute anything, but display would would be run |
| `--printshellcmds`, `-p` | `-p` | Print the shell commands that will be executed |
| `--cores`, `-c` | `-cN` | Use at most`N` CPU cores. Sets maximum number of cores requested from cluster or scheduler |
| `--jobs`, `-j` | `-jN` | Use at most `N` CPU cluster jobs in parallel. For local execution, use `--cores` |
| `--resources`, `--res` | `--res mem_mb=1000` | Define additional resources to constrain scheduler (e.g. allowed memory) |
| `--configfile`, `--configfiles` | `--configfile {target}` | Overwrite config file with file at provided file path |
| `--force`, `-f`| `-f` | Force execution of target/rule regardless of existing output | 
| `--forceall`, `-F` | `-F {target}` or `-F` | Force execution of selection rule (or first rule if rule is unspecified) and all rules it is dependent on regardless of existing output |
| `--forcerun` `-R` | `-R` | Force re-execution of given rule/file. Used if a rule has been changed. |
| `--until`, `-U` | `-U {target}` |Run pipeline until it reaches target rule/file |
| `--omit-from`, `-O` | `-O {target}` | Prevent execution of the target rule/file and any downstream rules/files |
| `-executor`, `-e` | `-e {executor}` i.e., `-e slurm` or `-e local` | Specify a custom executor - use `slurm` for HPC execution |
| `--workflow-profile` | `--workflow-profile {target}` | Path (relative to current directory) for workflow profile used to configure Snakemake with parameters for a specific workflow (e.g., allowed resources for Slurm) |
| `--configfile` | `----configfile {target}` | Specify or overwrite the config file of the workflow. Provide path relative to current directory. Allows separate config files for different analyses. |
