---
title: "Changing analysis parameters"
author: "Caitlin Cherryh"
date: "2025-02-18"
output: html_document
---

In some cases, the input choices for each of the steps might not work for your
individual analysis.

This file outlines the exact parameter choices used in each step.

### Modifying parameters for individual pipeline steps

The majority of changes needed to modify the `chromatin-assembly` pipeline for a
new analysis will be in the `config/chromatin_assembly_config.yml` file.

However, some of the pipeline steps may need to be modified for your particular 
dataset. 

For example, in Step 4 Kalign is called with the following command:
```
ngskit4b kalign -c25 -l25 -d50 -U4 -i reads_R1.fastq -u reads_R2.fastq 
-I GCF_900067755.1_pvi1.1_genomic_RM_nhmm_adapt 
-o kalign_pe_c25_l25_d50_U4.sam -F kalign_pe_c25_l25_d50_U4.log
```

This command uses the following settings:

- `-c25`
  - minimum chimeric length as a percentage of probe length
- `-l25`
  - after any end trimming, only accept read for further processing if read is at least this length
- `-d50` 
  - accept paired end alignments with observed insert sizes of at least this size
- `-U4`
  - paired end processing mode: 4 - paired end no orphan recovery treating orphan ends as SE

These settings may not be appropriate for your dataset. You can update them by
modifying the Snakemake rule.

### Snakemake rule structure
All Snakemake rules have the same structure. 

Here's a toy example for a rule called `copy_file`, which copies a file from
the `data/` directory to the `results/` directory.

```
rule copy_file:
  input:
    "data/{id}.txt"
  output:
    "results/{id}.txt"
  shell:
    "cat {input} > {output}"
```

The rule consists of the following components:

- `input` - input files
- `output` - output files
- `shell` - the shell command to generate input from the output (including 
calling other scripts or programs)

Other components present within the rule may include:

- `params` - other parameters needed for rule execution (e.g., adapters, controls, etc.)
- `message` - outputs the specified message in the console when executing that rule 
- `threads` - the number of threads to use for that rule
- `resources` - the computational resources (e.g., memory) to use for that rule
- `log` - specifies a log file to write information about the rule execution
- `envmodules` - environment modules for HPC pipeline use

### Updating a Snakemake rule

To update a Snakemake rule within the `chromatin-assembly` pipeline, edit the 
shell command. 

Let's take the example rule from above and say we want to add a message to the
console after the rule is complete. We do this by editing the shell command:

```
rule copy_file:
  input:
    "data/{id}.txt"
  output:
    "results/{id}.txt"
  shell:
    "cat {input} > {output} | echo 'Copy complete' "
```

When the rule is executed, it will now show the message `Copy complete` in the 
console.

## List of commands used within the pipeline

TODO update shell commands when pipeline steps completed
TODO change key variables to input in config file

The shell commands for each of the `chromatin-assembly` pipeline steps are 
listed below. For each step, we list the variables that you may wish to update. 
To update a step for your analysis requirements, modify the shell command for 
that rule in the file `workflow/Snakefile`.

### Step 1: `s1_mask_repeats`
Repeat masking and suffix array using RepeatMasker and kit4b

```
RepeatMasker -pa {params.cpus} -qq -dir {params.step1_dir} -lib {params.adapter} {input.ref_genome}
ngskit4b index -i {output.masked} -o {output.index} -r {params.ref_species} -T {params.cpus} -F {params.log}
```

### Step 2: `s2_raw_read_QC`
Raw read quality control with FastQC

```
fastqc -t 2 {input.r1} {input.r2} -o {params.outdir}
```

### Step 3: `s3_extract_UMI`
UMI extraction with FGBio and Picard

```

```

FGBio variables:

- `--read-structure=8M143T 8M143T`
- `--molecular-index-tags=ZA ZB`
- `--single-tag=RX`

### Step 4: `s4_read_alignment`
Align reads with kalign

```

```

kalign variables:

- `-c25`
  - minimum chimeric length as a percentage of probe length
- `-l25`
  - after any end trimming, only accept read for further processing if read is at least this length
- `-d50` 
  - accept paired end alignments with observed insert sizes of at least this size
- `-U4`
  - paired end processing mode: 4 - paired end no orphan recovery treating orphan ends as SE

In addition:

- Update the output file paths to reflect the changed input parameters

### Step 5: `s5_alignment_deduplication`
Remove PCR and optical duplicates from alignment with Picard

```

```

Picard variables:

- `REMOVE_DUPLICATES=TRUE`
- `BARCODE_TAG=RX`

### Step 6a: `s6a_two_bit_genome`
Generate 2Bit genome with faToTwoBit

```

```

### Step 6b: `s6b_effective_genome_size`
Calculate effective genome size with faCount

```

```

### Step 6c: `s6c_compute_GC_bias`
Compute GC bias with deeptools

```

```

deeptools variables:

- `--GCbiasFrequenciesFile`
- `--effectiveGenomeSize 1716675060`

### Step 6d: `s6d_correct_GC_bias`
Correct GC bias with deeptools

```
CMD="correctGCBias_kalign -p ${SLURM_CPUS_PER_TASK} -b ${BAM_DIR}/${SLURM_ARRAY_TASK_ID}_*_dedup.bam --effectiveGenomeSize 1716675060 -g ${BIT_DIR}/GCF_900067755.1_pvi1.1_genomic_RM_nhmm_adapt.2bit --GCbiasFrequenciesFile ${GC_COMPUTE_DIR}/${SLURM_ARRAY_TASK_ID}_*.txt -o ${GC_CORRECT_DIR}/${BASENAME}_gc_corrected.bam"
```

deeptools variables:

- `--GCbiasFrequenciesFile`
- `--effectiveGenomeSize 1716675060`

### Step 7a: `s7a_size_metrics`
Calculate alignment statistics with Picard

```

```

### Step 7b: `s7b_read_count`
Estimate mean nuclear genome cover with Picard

```

```

### Step 8: `s8_peak_analysis`
Peak analysis using DANPOS3

```

```


