---
title: "Input and output"
author: "Caitlin Cherryh"
date: "2025-02-18"
output: html_document
---

# Input

Running the `chromatin-assembly` pipeline requires at minimum, a set of reads 
and a reference genome. For convenience, we provide directories to store these
input files within the `data/` directory.

## i. Reads
Reads can (but do not have to be) placed in the `data/reads/` directory of the
`chromatin-assembly` repository.

### Selecting reads
TODO get Erin to write paragraph

### Read filenames
The Snakemake pipeline assumes that the file path for the reads fits the 
pattern `data/reads/{name}{lane_number}_R{read_number}.fastq.gz`, 
where:

- `data/reads/` is the directory containing the reads
- `{name}` is a string present in all read file names and ends with the string `"_L00"`
- `{lane_number}` is a single digit lane number from 1-9
- `{read_number}` is a single digit from 1-2

In other words, all reads have identical file paths varying only in the lane
number and read number. 

#### Example filenames
Choice of the `{name}` wildcard is important. The `{name}` should contain the
whole file name (excluding the file path) and end with the string `"_L00"`.


Given the `{name}` string `"133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L00"`, a valid 
example of reads would be the following set of files which share an identical 
`{name}` string but have different `{lane_number}` and `{read_number}` values:

- `133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L001_R1.fastq.gz`
- `133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L001_R2.fastq.gz`
- `133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L002_R1.fastq.gz`
- `133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L002_R2.fastq.gz`  

An invalid example of reads (as the `{name}` wildcard does not contain the 
whole file name):

- `copy_133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L001_R1.fastq.gz`
- `copy_133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L001_R2.fastq.gz`
- `copy_133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L002_R1.fastq.gz`
- `copy_133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L002_R2.fastq.gz`  

Another invalid example of reads (as the four files cannot be selected using a 
single `{name}` wildcard):

- `133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L001_R1.fastq.gz`
- `133165_H3NTTDSX3_GTGAAGTG-GAGCAATC_L001_R2.fastq.gz`
- `133165_H3NTTDSX3_L002_R1.fastq.gz`
- `133165_H3NTTDSX3_L002_R2.fastq.gz`

## ii. Reference genome
The reference genome can (but do not have to be) placed in the 
`data/reference_genome/` directory of the `chromatin-assembly` repository.

TODO get Erin to write paragraph

## iii. DANPOS input control
The input control can (but do not have to be) placed in the 
`data/input_control/` directory of the `chromatin-assembly` repository.

TODO get Erin to write paragraph

## iv. Config file
The path to the config file is `config/chromatin_assembly_config.yml`. You should
update the config file to match your input data and based on your HPC resources.

This file consists of three main sections: `input` (input parameters and paths 
to input data); `params` (for adapters and scripts used within the pipeline);
and Steps (to specify resources needed for each step). 

- `input`
  - `ref_species` - name of species (e.g., `"central_dragon"`)
  - `read_dir` - directory containing reads
  - `read_lanes` - the lanes (single digit from 1-9) of the reads you wish to include in this analysis
  - `read_path_pattern` - the string contained in all read file names, ending with `"_L00"`
  - `input_control_files1` - DANPOS input control files
  - `input_control_files2` - DANPOS input control files
- `params`
  - `adapters` - path to the adapters for your data
  - `faCount` - path to the faCount program (included in the `chromatin-assembly` repository)
  - `faToTwoBit` - path to the faToTwoBit program (included in the `chromatin-assembly` repository)
- Steps (from `step1` to `step8`)
  - Each step has a separate section with the following parameters, which are fed into SLURM when running the pipeline on a HPC:
    - `name` - name of each step (used for creating output directories)
    - `time` - allowed time for the given rule
    - `mem` - allowed memory for the given rule
    - `nodes` - number of nodes to allow for the given rule
    - `cpus` - the number of CPUs to allow for the given rule 

# Output

Three main outputs:

- 7a Size metrics
- 7b summary statistics
- 8 DANPOS (peak analysis)

